### ISSUE TITLE
BUG: Tried using template and immediately got a slew of PRs to update libraries

### ISSUE THREAD

**Issue by actuarysailor** [AlbertHernandez/github-action-nodejs-template#251]
# Prerequisites

- [X] I checked to make sure that this issue has not already been filed

The workflows you have seem great, they automatically update both python libraries and github actions.  That said, one of the PRs triggered by the workflow has me totally baffled.

https://github.com/actuarysailor/github-action-nodejs-local-file-copy/actions/runs/10646861707/job/29514176330?pr=3

**To Reproduce**
I would trigger your workflows, or have them run on a CRON schedule so that this stays up to date.

**Context**

Node Versions: 18.x and 20.x

**Comment by actuarysailor** [comment]
Also not understanding the error from this PR: https://github.com/actuarysailor/github-action-nodejs-local-file-copy/actions/runs/10646937852/job/29514341070

**Comment by AlbertHernandez** [comment]
I have seen this error couple of times, I think is related to `swc/cli` dependency that is not fully stable yet, need to investigate more to try to reproduce it, but maybe not using the `^` could help
