### ISSUE TITLE
FEATURE: README should get inputs and outputs auto documented

### ISSUE THREAD

**Issue by actuarysailor** [AlbertHernandez/github-action-nodejs-template#252]
# Prerequisites

- [x] I checked the documentation and found no answer

**Is your feature request related to a problem? Please describe.**
It would be helpful if we added an action or pre-commit hook to automatically generate the list of inputs and outputs in the readme file.

**Describe the solution you'd like**
I have seen with python and terraform many methods to auto document dependencies, versions, and inputs/outputs.  Would be nice to have that be a core feature for building new actions more easily.

**Describe alternatives you've considered**
None

**Comment by actuarysailor** [comment]
I will submit a PR for this

**Comment by AlbertHernandez** [comment]
@actuarysailor I totally agree, this feature would be really good, hoping to see that PR
